
title: BDIX SERVERS LIST BD ISP
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  BDIX CONNECTED MEDIA FTP & LIVE TV SERVERS LIST BD ISP

  BDIX CONNECTED MEDIA & FTP SERVERS
  TOP 50 ACTIVE SERVERS

author: Ahmed Sharif Khan Noor
start_year: 2023
current_year: { { site.time | date: "%Y" } }


baseurl: "/bdix-ftp-server-list" # the subpath of your site, e.g. /blog
url: "https://ahmedsharifkhan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

permalink: /:categories/:year/:month/:day/:title

# _config.yml
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:title/"

header_pages:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Resume
    url: /resume
  - title: CV
    url: /cv

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-admin